name: cypress_test

on:
  push:
    branches:
      - main

jobs:
  cypress_test:
    runs-on: ubuntu-latest
    container: cypress/included:8.3.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: cd test ; cypress run ; zip -r videos.zip cypress/videos/*
      - name: Test artifact
        uses: actions/upload-artifact@v2
        with:
          name: videos.zip
          path: ./videos.zip
