name: cypress_test

on:
  push:
    branches:
      - main

jobs:
  cypress_test:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:8.3.1
      volumes:
        - /tmp:/tmp
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run cypress
        run: |
          cd test
          cypress run
          cp -r cypress/videos/* /tmp/
      - name: Upload videos
        uses: actions/upload-artifact@v2
        with:
          name: videos
          path: /tmp/*
          retention-days: 1
