name: error_test

on:
  push:
    branches:
      - main

jobs:
  cypress_test_1:
    runs-on: ubuntu-latest
    steps:
      - run: ls -l43tr4t
  cypress_test_2:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: ["cypress_test_1"]
    steps:
      - run: ls435y435y
  cypress_test_3:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          ls
          ls -l
          ls -lh
          echo "test completed" > test.txt
          zip -r /tmp/test.zip *
          ls -l /tmp
        if: ${{ always() }}
