name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Test
        run: |
          echo "test"
          pwd
          ls -l
      - name: Slack Test
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: '#github-actions'
          slack-message: 'posting from a github action!'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
