#name: Test
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Run Test
#        run: |
#          echo "test"
#          pwd
#          ls -l > test.log
#      - name: Test artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name:test-txt
#          path: ./test.txt
#