name: zip-test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: |
          echo "test" > test.txt
          zip test.zip test.txt
          md5sum test.zip
